# Anodyne OS Drop-In Initialization Module
# Bypasses default text login boxes and routes the kernel target directly to the Kiosk service map

x1:23:respawn:/usr/bin/xinit /usr/bin/anodyne-kiosk-start.sh -- :0 -quiet
